LINK PENILAIAN
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_penilaian/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09
LINK SURAT TUGAS
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_surat_tugas/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09
LINK RESUME
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_resume/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09
LINK PENILAIAN PENJUALAN TAHUNAN
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_penjualan_tahunan/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TzZ0YTd5UDlyS3VXR0RRNk44aXk5UT09
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_penjualan_tahunan/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TWFwS1Zhdk1pRU9ZOVFvZE9Cb1VBdz09

LINK PENILAIAN KEUANGAN
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_keuangan/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TzZ0YTd5UDlyS3VXR0RRNk44aXk5UT09
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_keuangan/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TWFwS1Zhdk1pRU9ZOVFvZE9Cb1VBdz09


LINK PENILAIAN TKK
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_tenaga_kerja/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TzZ0YTd5UDlyS3VXR0RRNk44aXk5UT09
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_tenaga_kerja/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TWFwS1Zhdk1pRU9ZOVFvZE9Cb1VBdz09

LINK PENILAIAN PERALATAN
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_peralatan/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TzZ0YTd5UDlyS3VXR0RRNk44aXk5UT09
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_peralatan/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TWFwS1Zhdk1pRU9ZOVFvZE9Cb1VBdz09


LINK PENILAIAN SMAP
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_smap/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TzZ0YTd5UDlyS3VXR0RRNk44aXk5UT09
https://sertifikasi.lsbugapeknas.com/inbox/dokumen_smap/bEUxVzBtbnVlbTgvV1d6Ni9kYUJvZz09/TFFTMjBmeHBGMEtPa0NHd0tmWExiQT09/TWFwS1Zhdk1pRU9ZOVFvZE9Cb1VBdz09
