 "peralatan": [
        {
            "id": "46550",
            "updated": "2025-07-09 16:05:07",
            "created": null,
            "creator": null,
            "data_id": "8482",
            "seq": null,
            "jenis": "Pesawat Angkut",
            "tipe": null,
            "merek": "Caterpillar",
            "kapasitas": "",
            "tahun": "2016",
            "kondisi": null,
            "lokasi": null,
            "harga": null,
            "keterangan": null,
            "kepemilikan_peralatan": null,
            "file_doc_a": null,
            "memiliki_peralatan": null,
            "nomor_registrasi_peralatan": "00099092-S",
            "subvarian": "Bulldozer",
            "model_type": " D10R",
            "kapasitas_hasil_uji": "",
            "unit_satuan_kapasitas": "",
            "tahun_pembuatan": "2016",
            "provinsi": "31",
            "kab_kota": "3175",
            "jenis_bukti_kepemilikan": "Faktur Penjualan",
            "hasil_pemeriksaan_pengujian": null,
            "foto_plat_nama": null,
            "foto_tampak_depan_peralatan": "https://simpk.pu.go.id/assets/sdpk/ry0zv9ax6zmo2zcm-images_-_Copy_watermark.jpg",
            "foto_tampak_samping_peralatan": "https://simpk.pu.go.id/assets/sdpk/rfh9oldil5krn37h-images_watermark.jpg",
            "mapped_id": null,
            "nomor_nib": null,
            "no_seri": "80M04250",
            "varian": "Alat Berat",
            "pemilik": "PT Yarisa Cabang Group",
            "kode_provinsi": "31",
            "kode_kabkota": "3175",
            "foto_tampak_belakang_peralatan": "https://simpk.pu.go.id/assets/sdpk/38qwz8iwu0a6wete-DSC_0519_watermark.jpg",
            "kodefikasi_subvarian": "BDZ",
            "status_peralatan": "Sewa",
            "tanggal_mulai_sewa": "2025-06-30",
            "tanggal_akhir_sewa": "2026-06-29",
            "surat_perjanjian_sewa": "https://perizinan.pu.go.id/portal/admin/assets/upload/cdn/2025/07/09/8482/46550-686e30617e544.pdf",
            "nib": "0703240126035",
            "nomor_id_peralatan": "",
            "email": "groupyarisacabang@gmail.com"
        },
        {
            "id": "46551",
            "updated": "2025-07-09 16:05:08",
            "created": null,
            "creator": null,
            "data_id": "8482",
            "seq": null,
            "jenis": "Pesawat Angkut",
            "tipe": null,
            "merek": "MITSUBISHI",
            "kapasitas": "",
            "tahun": "2018",
            "kondisi": null,
            "lokasi": null,
            "harga": null,
            "keterangan": null,
            "kepemilikan_peralatan": null,
            "file_doc_a": null,
            "memiliki_peralatan": null,
            "nomor_registrasi_peralatan": "00099091-S",
            "subvarian": "Dump Truck",
            "model_type": "FN527MS",
            "kapasitas_hasil_uji": "",
            "unit_satuan_kapasitas": "",
            "tahun_pembuatan": "2018",
            "provinsi": "31",
            "kab_kota": "3175",
            "jenis_bukti_kepemilikan": "Bukti sah lainnya",
            "hasil_pemeriksaan_pengujian": null,
            "foto_plat_nama": null,
            "foto_tampak_depan_peralatan": "https://simpk.pu.go.id/assets/sdpk/6c2tbjfp7i90vkci-images_watermark.jpg",
            "foto_tampak_samping_peralatan": "https://simpk.pu.go.id/assets/sdpk/rzwn2zva4x19uz4u-images_-_Copy_watermark.jpg",
            "mapped_id": null,
            "nomor_nib": null,
            "no_seri": "W 8199 UA",
            "varian": "Truk",
            "pemilik": "PT Yarisa Cabang Group",
            "kode_provinsi": "31",
            "kode_kabkota": "3175",
            "foto_tampak_belakang_peralatan": "https://simpk.pu.go.id/assets/sdpk/c2mce5prqoe14cnu-KIR_W_8194_UA_NOV_2025_watermark.jpg",
            "kodefikasi_subvarian": "DTR",
            "status_peralatan": "Sewa",
            "tanggal_mulai_sewa": "2025-06-30",
            "tanggal_akhir_sewa": "2026-06-29",
            "surat_perjanjian_sewa": "https://perizinan.pu.go.id/portal/admin/assets/upload/cdn/2025/07/09/8482/46551-686e3061d5cba.pdf",
            "nib": "0703240126035",
            "nomor_id_peralatan": "",
            "email": "groupyarisacabang@gmail.com"
        },
        {
            "id": "46552",
            "updated": "2025-07-09 16:05:08",
            "created": null,
            "creator": null,
            "data_id": "8482",
            "seq": null,
            "jenis": "Pesawat Angkut",
            "tipe": null,
            "merek": "CATERPILLAR",
            "kapasitas": "",
            "tahun": "2016",
            "kondisi": null,
            "lokasi": null,
            "harga": null,
            "keterangan": null,
            "kepemilikan_peralatan": null,
            "file_doc_a": null,
            "memiliki_peralatan": null,
            "nomor_registrasi_peralatan": "00099093-S",
            "subvarian": "Loader",
            "model_type": "910F",
            "kapasitas_hasil_uji": "",
            "unit_satuan_kapasitas": "",
            "tahun_pembuatan": "2016",
            "provinsi": "31",
            "kab_kota": "3175",
            "jenis_bukti_kepemilikan": "Faktur Penjualan",
            "hasil_pemeriksaan_pengujian": null,
            "foto_plat_nama": null,
            "foto_tampak_depan_peralatan": "https://simpk.pu.go.id/assets/sdpk/6pejs10aw7iqa0tu-images_-_Copy_watermark.jpg",
            "foto_tampak_samping_peralatan": "https://simpk.pu.go.id/assets/sdpk/pkgux2ksos58pddi-images_watermark.jpg",
            "mapped_id": null,
            "nomor_nib": null,
            "no_seri": "1YK02171",
            "varian": "Alat Berat",
            "pemilik": "PT Yarisa Cabang Group",
            "kode_provinsi": "31",
            "kode_kabkota": "3175",
            "foto_tampak_belakang_peralatan": "https://simpk.pu.go.id/assets/sdpk/m871bp0o5jjikeiv-DSC_0519_watermark.jpg",
            "kodefikasi_subvarian": "WHL",
            "status_peralatan": "Sewa",
            "tanggal_mulai_sewa": "2025-06-30",
            "tanggal_akhir_sewa": "2026-06-29",
            "surat_perjanjian_sewa": "https://perizinan.pu.go.id/portal/admin/assets/upload/cdn/2025/07/09/8482/46552-686e306230cfb.pdf",
            "nib": "0703240126035",
            "nomor_id_peralatan": "",
            "email": "groupyarisacabang@gmail.com"
        }
    ],